import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css';
import Footer from "@/components/footer/Footer";
import Header from "@/components/header-component/Header";
import NiftyStickyHeader from "@/components/header-component/NiftyStickyHeader";

export const metadata = {
  title: "MM-Next14",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
 


        {" "}
       
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
        />
      </head>
      <body>
        <NiftyStickyHeader />
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
